FROM node:latest as production

WORKDIR /app

COPY package.json /app

RUN yarn install

RUN npm install --save react-apexcharts apexcharts --force

COPY . .

RUN yarn build

FROM nginx:1.12-alpine

COPY --from=production /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]