version: "3.7"

services:
  prod-database:
    container_name: prod-database
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ebn_back/database
    env_file:
      - ebn_back/.env.prod.docker
    ports:
      - "3306:3306"

  prod-phpmyadmin:
    container_name: prod-phpmyadmin
    depends_on:
      - prod-database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8778:80"
    environment:
      PMA_HOST: prod-database
      MYSQL_ROOT_PASSWORD: ebnrootd

  prod-api:
    container_name: prod-api
    env_file:
      - ebn_back/.env.prod.docker
    build:
      context: ebn_back
      dockerfile: Dockerfile.prod
    depends_on:
      - prod-database
    ports:
      - "5454:5454"
    restart: always

  prod-web:
    container_name: prod-web
    build:
      context: ebn_front
      dockerfile: Dockerfile.prod
    depends_on:
      - prod-api
    ports:
      - "3838:3000"
    restart: always