version: "3.7"

services:
  dev-database:
    container_name: dev-database
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: ebn_back/database
    env_file:
      - ebn_back/.env.docker
    ports:
      - "3306:3306"

  dev-phpmyadmin:
    container_name: dev-phpmyadmin
    depends_on:
      - dev-database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: dev-database
      MYSQL_ROOT_PASSWORD: ebnroot

  dev-api:
    container_name: dev-api
    env_file:
      - ebn_back/.env.docker
    build:
      context: ebn_back
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    depends_on:
      - dev-database
    volumes:
      - ./ebn_back:/usr/src/app
    ports:
      - "5454:5454"
    restart: always

  dev-web:
    container_name: dev-web
    build:
      context: ebn_front
      dockerfile: Dockerfile.dev
    depends_on:
      - dev-api
    volumes:
      - ./ebn_front:/app
    ports:
      - "3000:3000"
    restart: always