FROM node:latest as production

WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN npm install -g npm@8.12.1

RUN npm install

COPY . .

RUN npm run build

FROM node:latest

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY --from=production /usr/src/app/dist ./dist

EXPOSE 5454

CMD ["node", "dist/main"]