version: "3.7"

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: database
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ebnroot
      MYSQL_DATABASE: ebn_database
      MYSQL_USER: ebn
      MYSQL_PASSWORD: ebnroot
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ebnroot
