version: "3.7"

services:
  database_ebn:
    container_name: database_ebn
    image: mysql:8.0
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: database
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - database_ebn
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8088:80"
    environment:
      PMA_HOST: database_ebn
      MYSQL_ROOT_PASSWORD: ebnroot

  dev:
    container_name: ebn-dev
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    depends_on:
      - database_ebn
    ports:
      - "5454:5454"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always